# Change these first
owner: jackzmc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: HS - a.us-central.servers.jackz.me
    url: http://mc.jackz.me
  - name: VPS1 - a.ca-east.servers.jackz.me
    url: vps1.jackz.me
  - name: LGS - US Central B - b.us-central.servers.jackz.me
    url: http://lgs.jackz.me
  - name: US East A - a.us-east.servers.jackz.me
    url: http://a.us-east.servers.jackz.me
  - name: US East B - b.us-east.servers.jackz.me
    url: http://b.us-east.servers.jackz.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jackz.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Server Uptime**
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
